// components/ProgressView.tsx
'use client';

import { SECTIONS, TIERS, AVATAR_STAGES, getAvatarStage } from '@/lib/constants';
import { useApp } from '@/lib/context';
import { Avatar } from './Avatar';

export function ProgressView() {
  const { entries, totalXP, level, xpInLevel } = useApp();

  const stage = getAvatarStage(level);
  const nextStage = AVATAR_STAGES.find(s => s.minLevel > level);
  const tierCounts = TIERS.map(t => ({ ...t, count: entries.filter(e => e.tier === t.id).length }));
  const sectionCounts = SECTIONS.map(s => ({ ...s, count: entries.filter(e => e.section === s.id).length }));

  return (
    <>
      <div className="progress-section">
        <h3 className="progress-title">Your Avatar</h3>
        <div className="avatar-showcase">
          <div className="avatar-showcase-inner">
            <Avatar level={level} size={140} />
            <div className="avatar-stage-name">{stage.name}</div>
            <div className="avatar-stage-desc">{stage.description}</div>
          </div>
        </div>
        {nextStage && (
          <div className="next-avatar">
            <div className="next-avatar-label">Next Evolution</div>
            <div className="next-avatar-name">{nextStage.name}</div>
            <div className="next-avatar-xp">
              Reach Level {nextStage.minLevel} ({(nextStage.minLevel - 1) * 100 - totalXP} XP to go)
            </div>
          </div>
        )}
      </div>

      <div className="progress-section">
        <h3 className="progress-title">Level Progress</h3>
        <div className="level-display">
          <div className="level-number">{level}</div>
          <div className="level-label">Level</div>
          <div className="xp-bar-container">
            <div className="xp-bar-header">
              <span className="xp-bar-label">Progress to Level {level + 1}</span>
              <span className="xp-bar-value">{xpInLevel} / 100 XP</span>
            </div>
            <div className="xp-bar">
              <div className="xp-bar-fill" style={{ width: `${xpInLevel}%` }} />
            </div>
          </div>
        </div>
      </div>

      <div className="progress-section">
        <h3 className="progress-title">Quests by Tier</h3>
        <div className="tier-list">
          {tierCounts.map(t => (
            <div key={t.id} className="tier-btn" style={{ cursor: 'default' }}>
              <div className="tier-rank">{t.count}</div>
              <div className="tier-info">
                <div className="tier-name">{t.name}</div>
                <div className="tier-desc">{t.description}</div>
              </div>
              <div className="tier-xp">{t.count * t.xp} XP</div>
            </div>
          ))}
        </div>
      </div>

      <div className="progress-section">
        <h3 className="progress-title">Realms Explored</h3>
        <div className="realm-progress">
          {sectionCounts.map(s => (
            <div key={s.id} className="realm-progress-row">
              <div className="realm-progress-icon">{s.icon}</div>
              <div className="realm-progress-info">
                <div className="realm-progress-name">{s.name}</div>
              </div>
              <div className="realm-progress-count">{s.count}</div>
            </div>
          ))}
        </div>
      </div>
    </>
  );
}

// components/ProgressView.vue
<script setup lang="ts">
import { computed } from 'vue'
import { SECTIONS, TIERS, AVATAR_STAGES, getAvatarStage } from '~/composables/constants'

const { entries, totalXP, level, xpInLevel } = useApp()

const stage = computed(() => getAvatarStage(level.value))
const nextStage = computed(() => AVATAR_STAGES.find(s => s.minLevel > level.value))

const tierCounts = computed(() => {
  return TIERS.map(t => ({
    ...t,
    count: entries.value.filter(e => e.tier === t.id).length
  }))
})

const sectionCounts = computed(() => {
  return SECTIONS.map(s => ({
    ...s,
    count: entries.value.filter(e => e.section === s.id).length
  }))
})

const xpToNextStage = computed(() => {
  if (!nextStage.value) return 0
  return (nextStage.value.minLevel - 1) * 100 - totalXP.value
})
</script>

<template>
  <div>
    <div class="progress-section">
      <h3 class="progress-title">Your Avatar</h3>
      <div class="avatar-showcase">
        <div class="avatar-showcase-inner">
          <Avatar :level="level" :size="140" />
          <div class="avatar-stage-name">{{ stage.name }}</div>
          <div class="avatar-stage-desc">{{ stage.description }}</div>
        </div>
      </div>
      <div v-if="nextStage" class="next-avatar">
        <div class="next-avatar-label">Next Evolution</div>
        <div class="next-avatar-name">{{ nextStage.name }}</div>
        <div class="next-avatar-xp">
          Reach Level {{ nextStage.minLevel }} ({{ xpToNextStage }} XP to go)
        </div>
      </div>
    </div>

    <div class="progress-section">
      <h3 class="progress-title">Level Progress</h3>
      <div class="level-display">
        <div class="level-number">{{ level }}</div>
        <div class="level-label">Level</div>
        <div class="xp-bar-container">
          <div class="xp-bar-header">
            <span class="xp-bar-label">Progress to Level {{ level + 1 }}</span>
            <span class="xp-bar-value">{{ xpInLevel }} / 100 XP</span>
          </div>
          <div class="xp-bar">
            <div class="xp-bar-fill" :style="{ width: `${xpInLevel}%` }" />
          </div>
        </div>
      </div>
    </div>

    <div class="progress-section">
      <h3 class="progress-title">Quests by Tier</h3>
      <div class="tier-list">
        <div v-for="t in tierCounts" :key="t.id" class="tier-btn" style="cursor: default">
          <div class="tier-rank">{{ t.count }}</div>
          <div class="tier-info">
            <div class="tier-name">{{ t.name }}</div>
            <div class="tier-desc">{{ t.description }}</div>
          </div>
          <div class="tier-xp">{{ t.count * t.xp }} XP</div>
        </div>
      </div>
    </div>

    <div class="progress-section">
      <h3 class="progress-title">Realms Explored</h3>
      <div class="realm-progress">
        <div v-for="s in sectionCounts" :key="s.id" class="realm-progress-row">
          <div class="realm-progress-icon">{{ s.icon }}</div>
          <div class="realm-progress-info">
            <div class="realm-progress-name">{{ s.name }}</div>
          </div>
          <div class="realm-progress-count">{{ s.count }}</div>
        </div>
      </div>
    </div>
  </div>
</template>
