// components/RealmSelect.vue
<script setup lang="ts">
import { SECTIONS, type Section } from '~/composables/constants'

const { entries } = useApp()

const emit = defineEmits<{
  (e: 'select', realm: Section): void
}>()

function getCount(sectionId: string) {
  return entries.value.filter(e => e.section === sectionId).length
}
</script>

<template>
  <div class="realm-grid">
    <div
      v-for="section in SECTIONS"
      :key="section.id"
      class="realm-card"
      :style="{ '--realm-color': section.color }"
      @click="emit('select', section)"
    >
      <span v-if="getCount(section.id) > 0" class="realm-count">
        {{ getCount(section.id) }} complete
      </span>
      <div class="realm-header">
        <div class="realm-icon-wrap">
          <div class="realm-icon-bg" />
          <div class="realm-icon">{{ section.icon }}</div>
        </div>
        <div class="realm-info">
          <div class="realm-name">{{ section.name }}</div>
          <div class="realm-subtitle">{{ section.description }}</div>
        </div>
        <div class="realm-arrow">→</div>
      </div>
    </div>
  </div>
</template>

// components/RealmSelect.tsx
'use client';

import { SECTIONS, Section } from '@/lib/constants';
import { useApp } from '@/lib/context';

interface RealmSelectProps {
  onSelect: (realm: Section) => void;
}

export function RealmSelect({ onSelect }: RealmSelectProps) {
  const { entries } = useApp();

  return (
    <div className="realm-grid">
      {SECTIONS.map(section => {
        const count = entries.filter(e => e.section === section.id).length;
        return (
          <div
            key={section.id}
            className="realm-card"
            onClick={() => onSelect(section)}
            style={{ '--realm-color': section.color } as React.CSSProperties}
          >
            {count > 0 && <span className="realm-count">{count} complete</span>}
            <div className="realm-header">
              <div className="realm-icon-wrap">
                <div className="realm-icon-bg" />
                <div className="realm-icon">{section.icon}</div>
              </div>
              <div className="realm-info">
                <div className="realm-name">{section.name}</div>
                <div className="realm-subtitle">{section.description}</div>
              </div>
              <div className="realm-arrow">→</div>
            </div>
          </div>
        );
      })}
    </div>
  );
}
